config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :create]
  resources :weapons, only: [:index, :create, :destroy, :show]

  resources :enemies, only: [:update, :destroy, :index, :show, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/enemy.rb
class Enemy < ApplicationRecord
  enum kind: [ :goblin, :orc, :demon, :dragon]

  validates :level, numericality: { greater_than: 0, less_than_or_equal_to: 99 }
  validates_presence_of :name, :power_base, :power_step, :level, :kind

  def current_power
    power_base + ((level - 1) * power_step)
  end
end

app/models/user.rb
class User < ApplicationRecord
  enum kind: [ :knight, :wizard ]
  validates :level, numericality: { greater_than: 0, less_than_or_equal_to: 99 }

  def title
    "#{self.kind} #{self.nickname} ##{self.level}"
  end
end

app/models/weapon.rb
class Weapon < ApplicationRecord
  validates :level, numericality: { greater_than: 0, less_than_or_equal_to: 99 }

  def current_power
    self.power_base + ((self.level - 1) * self.power_step)
  end

  def title
    "#{self.name} ##{self.level}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/enemies_controller.rb
class EnemiesController < ApplicationController
  before_action :set_enemy, except: [:index, :create]

  def index
    @enemies = Enemy.all
    render json: @enemies
  end

  def show
    render json: @enemy
  end
  def update
    if @enemy.update(enemy_params)
      render json: @enemy, status: 200
    else
      render json: { errors: @enemy.errors }, status: :unprocessable_entity
    end
  end

  def create
    @enemy = Enemy.create(enemy_params)
    if @enemy.save
      render json: @enemy, status: 201
    else
      render json: { errors: @enemy.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    @enemy.destroy
    head 204
  end

  private
  def enemy_params
    params.require(:enemy).permit(:name, :power_base, :power_step, :level, :kind)
  end

  def set_enemy
    @enemy = Enemy.find(params[:id])
  rescue ActiveRecord::RecordNotFound => e
    render json: { message: e.message }, status: :not_found
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def create
    @user = User.create(user_params)
    if @user.save
      redirect_to users_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :kind, :level)
  end
end

app/controllers/weapons_controller.rb
class WeaponsController < ApplicationController
  def index
    @weapons = Weapon.all
  end

  def create
    @weapon = Weapon.new(weapon_params)
    if @weapon.save
      redirect_to weapons_path
    else
      redirect_to weapons_path, status: :unprocessable_entity
    end
  end

  def destroy
    @weapon = Weapon.find(params[:id])
    @weapon.destroy
    redirect_to weapons_path
  end

  def show
    @weapon = Weapon.find(params[:id])
  end

  private

  def weapon_params
    params.require(:weapon).permit(:name, :description, :power_base, :power_step, :level)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/enemies/destroy.html.erb
<h1>Enemies#destroy</h1>
<p>Find me in app/views/enemies/destroy.html.erb</p>

app/views/enemies/update.html.erb
<h1>Enemies#update</h1>
<p>Find me in app/views/enemies/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HeroicSpec</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <p><%= user.title %></p>
<% end %>

app/views/weapons/create.html.erb
<%= form_with model: @weapon do |form| %>

  <% if @weapon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@weapon.errors.count, "error") %> prohibited this weapon from being saved:</h2>

      <ul>
        <% @weapon.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :power_base %>
    <%= form.number_field :power_base %>
  </div>

  <div class="field">
    <%= form.label :power_step %>
    <%= form.number_field :power_step %>
  </div>

  <div class="field">
    <%= form.label :level %>
    <%= form.number_field :level %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/weapons/delete.html.erb
<h1>Weapons#delete</h1>
<p>Find me in app/views/weapons/delete.html.erb</p>

app/views/weapons/index.html.erb
<% @weapons.each do |weapon| %>
  <p><%= weapon.name %></p>
  <p><%= weapon.current_power %></p>
  <p><%= weapon.title %></p>
  <% link_to 'show weapon', weapon_path(weapon) %>
<% end %>

app/views/weapons/show.html.erb
<%= @weapon.name %>
<%= @weapon.level %>
<%= @weapon.description %>
<%= @weapon.power_base %>
<%= @weapon.power_step %>
<%= @weapon.current_power %>
<%= @weapon.title %>